export const GET_ADS_ALL = "GET_ADS_ALL";
export const GET_ADS_ALL_SUCCESS = "GET_ADS_ALL_SUCCESS";
export const GET_ADS_BY_LOCATION = "GET_ADS_ALL_BY_LOCATION";
export const GET_ADS_BY_LOCATION_SUCCESS = "GET_ADS_ALL_BY_LOCATION_SUCCESS";
export const GET_ADS_JOB_PAGE = "GET_ADS_JOB_PAGE";
export const GET_ADS_JOB_PAGE_SUCCESS = "GET_ADS_JOB_PAGE_SUCCESS";
