export const GET_ALL_RECORD_BY_USER = "GET_ALL_RECORD_BY_USER";
export const GET_ALL_RECORD_BY_USER_SUCCESS = "GET_ALL_RECORD_BY_USER_SUCCESS";
export const GET_RECORD_BY_ID = "GET_RECORD_BY_ID";
export const GET_RECORD_BY_ID_SUCCESS = "GET_RECORD_BY_ID_SUCCESS";
export const GET_RECORD_BY_USER_ID = "GET_RECORD_BY_USER_ID";
export const GET_RECORD_BY_USER_ID_SUCCESS = "GET_RECORD_BY_USER_ID_SUCCESS";

export const UPDATE_RECORD = "UPDATE_RECORD";
export const CREATE_RECORD = "CREATE_RECORD";

export const CHECK_RECORD_USER_EXIST = "CHECK_RECORD_USER_EXIST";
export const CHECK_RECORD_USER_EXIST_SUCCESS =
  "CHECK_RECORD_USER_EXIST_SUCCESS";
