export const GET_ALL_WORK_LOCATION = "GET_ALL_WORK_LOCATION";
export const GET_ALL_WORK_LOCATION_SUCCESS = "GET_ALL_WORK_LOCATION_SUCCESS";
export const GET_WORK_LOCATION_BY_COMPANY = "GET_WORK_LOCATION_BY_COMPANY";
export const GET_WORK_LOCATION_BY_COMPANY_SUCCESS =
  "GET_WORK_LOCATION_BY_COMPANY_SUCCESS";
export const CREATE_WORK_LOCATION = "CREATE_WORK_LOCATION";
export const DELETE_WORK_LOCATION = "DELETE_WORK_LOCATION";
export const UPDATE_WORK_LOCATION = "UPDATE_WORK_LOCATION";
