export const GET_ALL_SCHEDULE_INTERVIEW = "GET_ALL_SCHEDULE_INTERVIEW";
export const GET_ALL_SCHEDULE_INTERVIEW_SUCCESS =
  "GET_ALL_SCHEDULE_INTERVIEW_SUCCESS";

export const GET_SCHEDULE_INTERVIEW_BY_ID = "GET_SCHEDULE_INTERVIEW_BY_ID";
export const GET_SCHEDULE_INTERVIEW_BY_ID_SUCCESS =
  "GET_SCHEDULE_INTERVIEW_BY_ID_SUCCESS";

export const UPDATE_SCHEDULE_INTERVIEW = "UPDATE_SCHEDULE_INTERVIEW";
export const CREATE_SCHEDULE_INTERVIEW = "CREATE_SCHEDULE_INTERVIEW";

export const CONFIRM_THE_SCHEDULE_INTERVIEW = "CONFIRM_THE_SCHEDULE_INTERVIEW";
export const CANCEL_THE_SCHEDULE_INTERVIEW = "CANCEL_THE_SCHEDULE_INTERVIEW";
