export const GET_ALL_BLOG = "GET_ALL_BLOG";
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS";

export const GET_BLOG_BY_SLUG = "GET_BLOG_BY_SLUG";
export const GET_BLOG_BY_SLUG_SUCCESS = "GET_BLOG_BY_SLUG_SUCCESS";
