export const GET_ALL_RECRUITMENT = "GET_ALL_RECRUITMENT";
export const GET_RECRUITMENT_BY_COMPANY = "GET_RECRUITMENT_BY_COMPANY";
export const GET_RECRUITMENT_BY_USER = "GET_RECRUITMENT_BY_USER";
export const GET_ALL_RECRUITMENT_SUCCESS = "GET_ALL_RECRUITMENT_SUCCESS";
export const GET_RECRUITMENT_BY_ID = "GET_RECRUITMENT_BY_ID";
export const GET_RECRUITMENT_BY_ID_SUCCESS = "GET_RECRUITMENT_BY_ID_SUCCESS";
export const GET_RECRUITMENT_BY_SLUG = "GET_RECRUITMENT_BY_SLUG";
export const GET_RECRUITMENT_BY_SLUG_SUCCESS =
  "GET_RECRUITMENT_BY_SLUG_SUCCESS";

export const SET_SEEN_RECRUITMENT = "SET_SEEN_RECRUITMENT";
export const SET_APPLIED_RECRUITMENT = "SET_APPLIED_RECRUITMENT";
export const SET_APPLIED_USER_TO_APPROVED = "SET_APPLIED_USER_TO_APPROVED";
export const SET_SAVED_RECRUITMENT = "SET_SAVED_RECRUITMENT";
export const REMOVE_SAVED_RECRUITMENT = "REMOVE_SAVED_RECRUITMENT";

export const CREATE_RECRUITMENT = "CREATE_RECRUITMENT";

export const GET_BEST_RECRUITMENT = "GET_BEST_RECRUITMENT";
export const GET_BEST_RECRUITMENT_SUCCESS = "GET_BEST_RECRUITMENT_SUCCESS";

export const GET_MOST_KEYWORD = "GET_MOST_KEYWORD";
export const GET_MOST_KEYWORD_SUCCESS = "GET_MOST_KEYWORD_SUCCESS";

export const SET_SORT_TYPE_SELECTED = "SET_SORT_TYPE_SELECTED";
