export const GET_CONTENT_WEBSITE = "GET_CONTENT_WEBSITE";
export const GET_CONTENT_WEBSITE_SUCCESS = "GET_CONTENT_WEBSITE_SUCCESS";

export const GET_SEO_WEBSITE = "GET_SEO_WEBSITE";
export const GET_SEO_WEBSITE_SUCCESS = "GET_SEO_WEBSITE_SUCCESS";

export const GET_FOOTER_CONTENT_OF_PROJECT = "GET_FOOTER_CONTENT_OF_PROJECT";
export const GET_FOOTER_CONTENT_OF_PROJECT_SUCCESS =
  "GET_FOOTER_CONTENT_OF_PROJECT_SUCCESS";
