export const GET_ALL_CATEGORY_1_JOB = "GET_ALL_CATEGORY_1_JOB";
export const GET_ALL_CATEGORY_1_JOB_SUCCESS = "GET_ALL_CATEGORY_1_JOB_SUCCESS";

export const GET_ALL_CATEGORY_2_JOB = "GET_ALL_CATEGORY_2_JOB";
export const GET_ALL_CATEGORY_2_JOB_SUCCESS = "GET_ALL_CATEGORY_2_JOB_SUCCESS";

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";

export const SET_CATEGORY_SELECTED = "SET_CATEGORY_SELECTED";
