export const GET_ALL_COMPANY = "GET_ALL_COMPANY";
export const GET_ALL_COMPANY_SUCCESS = "GET_ALL_COMPANY_SUCCESS";

export const GET_COMPANY = "GET_COMPANY";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";

export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const UPDATE_COMPANY_PROVINCE = "UPDATE_COMPANY_PROVINCE";

export const SET_SUBSCRIBE_COMPANY = "SET_SUBSCRIBE_COMPANY";
export const SET_SEEN_COMPANY = "SET_SEEN_COMPANY";

export const GET_NEWEST_COMPANY = "GET_NEWEST_COMPANY";
export const GET_NEWEST_COMPANY_SUCCESS = "GET_NEWEST_COMPANY_SUCCESS";

export const GET_MOST_VIEW_COMPANY = "GET_MOST_VIEW_COMPANY";
export const GET_MOST_VIEW_COMPANY_SUCCESS = "GET_MOST_VIEW_COMPANY_SUCCESS";

export const GET_MOST_APPLIED_COMPANY = "GET_MOST_APPLIED_COMPANY";
export const GET_MOST_APPLIED_COMPANY_SUCCESS =
  "GET_MOST_APPLIED_COMPANY_SUCCESS";

export const GET_MOST_RECRUITING_COMPANY = "GET_MOST_RECRUITING_COMPANY";
export const GET_MOST_RECRUITING_COMPANY_SUCCESS =
  "GET_MOST_RECRUITING_COMPANY_SUCCESS";

export const GET_COMPANY_BY_SLUG = "GET_COMPANY_BY_SLUG";
export const GET_COMPANY_BY_SLUG_SUCCESS = "GET_COMPANY_BY_SLUG_SUCCESS";
