export const GET_PROVINCES = "GET_PROVINCES";
export const GET_PROVINCE_SUCCESS = "GET_PROVINCE_SUCCESS";

export const GET_DISTRICTS = "GET_DISTRICTS";
export const GET_DISTRICTS_SUCCESS = "GET_DISTRICTS_SUCCESS";

export const GET_WARDS = "GET_WARDS";
export const GET_WARDS_SUCCESS = "GET_WARDS_SUCCESS";

export const GET_STREETS_BY_PROVINCE_AND_DISTRICT =
  "GET_STREETS_BY_PROVINCE_AND_DISTRICT";
export const GET_STREETS_BY_PROVINCE_AND_DISTRICT_SUCCESS =
  "GET_STREETS_BY_PROVINCE_AND_DISTRICT_SUCCESS";

export const SET_PROVINCE_SELECTED = "SET_PROVINCE_SELECTED";
