export const GET_ALL_REQUEST_REVIEW = "GET_ALL_REQUEST_REVIEW";
export const GET_ALL_REQUEST_REVIEW_SUCCESS = "GET_ALL_REQUEST_REVIEW_SUCCESS";

export const GET_EVALUATE_BY_USER = "GET_EVALUATE_BY_USER";
export const GET_EVALUATE_BY_USER_SUCCESS = "GET_EVALUATE_BY_USER_SUCCESS";

export const CREATE_REQUEST_REVIEW = "CREATE_REQUEST_REVIEW";
