export const GET_ALL_CAREER_SUCCESS = "GET_ALL_CAREER_SUCCESS";

export const GET_ALL_JOB_TYPE = "GET_ALL_JOB_TYPE";
export const GET_ALL_JOB_TYPE_SUCCESS = "GET_ALL_JOB_TYPE_SUCCESS";

export const GET_ALL_JOB_LEVEL = "GET_ALL_JOB_LEVEL";
export const GET_ALL_JOB_LEVEL_SUCCESS = "GET_ALL_JOB_LEVEL_SUCCESS";

export const GET_ALL_JOB_LEVEL_FILTER = "GET_ALL_JOB_LEVEL_FILTER";
export const GET_ALL_JOB_LEVEL_FILTER_SUCCESS =
  "GET_ALL_JOB_LEVEL_FILTER_SUCCESS";

export const GET_ALL_LEVEL_PRICE = "GET_ALL_LEVEL_PRICE";
export const GET_ALL_LEVEL_PRICE_SUCCESS = "GET_ALL_LEVEL_PRICE_SUCCESS";

export const SET_JOB_TYPE_SELECTED = "SET_JOB_TYPE_SELECTED";
export const SET_JOB_LEVEL_SELECTED = "SET_JOB_LEVEL_SELECTED";
export const SET_LEVEL_PRICE_SELECTED = "SET_LEVEL_PRICE_SELECTED";
