export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SET_IS_AUTH = "SET_IS_AUTH";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";

export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";

export const CREATE_CANDIDATE = "CREATE_CANDIDATE";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";

export const REGISTER_OTP_VOICE = "REGISTER_OTP_VOICE";

export const SEND_OTP_VOICE = "SEND_OTP_VOICE";

export const RESET_PASSWORD_OTP_VOICE = "RESET_PASSWORD_OTP_VOICE";

export const VERIFY_OTP_VOICE = "VERIFY_OTP_VOICE";
export const VERIFY_OTP_RESET_PASSWORD = "VERIFY_OTP_RESET_PASSWORD";
