export const GET_ALL_STATIC_PAGES = "GET_ALL_STATIC_PAGES";
export const GET_ALL_STATIC_PAGES_SUCCESS = "GET_ALL_STATIC_PAGES_SUCCESS";

export const GET_STATIC_PAGE_BY_SLUG = "GET_STATIC_PAGE_BY_SLUG";
export const GET_STATIC_PAGE_BY_SLUG_SUCCESS =
  "GET_STATIC_PAGE_BY_SLUG_SUCCESS";
