export const GET_ALL_INVITATION_APPLY = "GET_ALL_INVITATION_APPLY";
export const GET_ALL_INVITATION_APPLY_SUCCESS =
  "GET_ALL_INVITATION_APPLY_SUCCESS";

export const GET_INVITATION_APPLY_BY_ID = "GET_INVITATION_APPLY_BY_ID";
export const GET_INVITATION_APPLY_BY_ID_SUCCESS =
  "GET_INVITATION_APPLY_BY_ID_SUCCESS";

export const UPDATE_INVITATION_APPLY = "UPDATE_INVITATION_APPLY";
export const CREATE_INVITATION_APPLY = "CREATE_INVITATION_APPLY";

export const CONFIRM_THE_INVITATION = "CONFIRM_THE_INVITATION";
