export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const CHECK_PROFILE_USER_EXIST = "CHECK_PROFILE_USER_EXIST";
export const CHECK_PROFILE_USER_EXIST_SUCCESS =
  "CHECK_PROFILE_USER_EXIST_SUCCESS";
